---
title: "cran-comments"
output: github_document
---

<!-- cran-comments.md is generated from cran-comments.Rmd. -->

## New submission

This patch comes with the following changes:

- Due to a misconception of object type tests the same value was reported for
  each rl value if the cics model was the appropriate model although the
  correct values were calculated. Now, the correct values (i.e. Delta, WCSL
  and Shelf.Life) are reported.
- The output of the summary() function was harmonised for cics models on the 
  one hand and dics / dids models on the other.
- The deprecated ggplot2 function aes_string() has been replaced by aes().
  Variables containing column names as a character vector (var_name) are
  now called via .data[[var_name]]. In addition, size has been replaced by
  linewidth when used in the geom_line() function. In addition, visible binding
  for global variavles was added.

## Test environments

- Local windows-x86_64-w64-mingw32/x64 (R 4.2.2)
- Win-builder windows-x86_64-w64-mingw32/x64 (R 4.1.3)
- Win-builder windows-x86_64-w64-mingw32/x64 (R 4.2.2)
- Win-builder windows-x86_64-w64-mingw32/x64 (R-devel)
- R-hub Windows Server 2022, 64-bit (R-devel)
- R-hub Ubuntu Linux 20.04.1 LTS, GCC (R-release)
- R-hub Fedora Linux, clang, gfortran (R-devel)
- R-hub macOS 10.13.6 High Sierra (R-release)

## R CMD check results

0 errors | 0 warnings | 0 note
  
Possibly misspelled words in DESCRIPTION: the indicated words are names or abbreviations. None of the words is misspelled.

## Downstream dependencies

There are no downstream dependencies for this package.
